image_width: 800
image_height: 600
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1802.81746,    0.     ,  123.48141,
            0.     , 1816.16279,   86.12575,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.106804, 0.261460, 0.005970, 0.013177, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1814.83826,    0.     ,  124.6989 ,    0.     ,
            0.     , 1823.72632,   86.51788,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
